### ISSUE TITLE
Failed to build the conhost project after 13e058d9

### ISSUE THREAD

**Issue by skyline75489** [microsoft/terminal#9128]
MSBulid failed with:

```text
src\server\IoDispatchers.cpp(21,10): Error C1083: Cannot open include file: 'IConsoleHandoff.h': No such file or directory
```

I'm positive that I'm not the first one that noticed this...

**Comment by DHowett** [comment]
You're going to be the first one who noticed this. :smile:

**Comment by DHowett** [comment]
@miniksa FYI for tomorrow.

@skyline75489 if you want to try fixing it :smile:
