### PR TITLE
Fix the Host Proxy DLL reference in ServerLib

### LINKED ISSUE #9128: Failed to build the conhost project after 13e058d9
MSBulid failed with:

```text
src\server\IoDispatchers.cpp(21,10): Error C1083: Cannot open include file: 'IConsoleHandoff.h': No such file or directory
```

I'm positive that I'm not the first one that noticed this...

### PR DESCRIPTION
**Pull request by DHowett**
Fixes #9128

### CODE REVIEW

**Comment by skyline75489** [comment]
Well it surely fixes the compilation error. But I don’t feel eligible to approve or disapprove this change, though. I have no idea what’s happening...

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Dustin L. Howett <notifications@github.com>
发送时间: Friday, February 12, 2021 1:48:42 PM
收件人: microsoft/terminal <terminal@noreply.github.com>
抄送: Chester Liu <skyline75489@outlook.com>; Review requested <review_requested@noreply.github.com>
主题: Re: [microsoft/terminal] Fix the Host Proxy DLL reference in ServerLib (#9129)


@DHowett<https://github.com/DHowett> requested your review on: #9129<https://github.com/microsoft/terminal/pull/9129> Fix the Host Proxy DLL reference in ServerLib.

―

**Review by zadjii-msft — APPROVED** [review]

**Comment by miniksa** [comment]
This is your fault @zadjii-msft. I warned you about stairs.
image

**Review by miniksa — APPROVED** [review]
