### ISSUE TITLE
Build fails after commit 62765f1

### ISSUE THREAD

**Issue by j4james** [microsoft/terminal#4285]
# Environment

```none
Windows build number: Version 10.0.18362.535

Any other software?
Visual Studio 2019 version 16.4.2
```

# Steps to reproduce

1. Checkout commit 62765f152e1fc9732a2ff212c9b98c1d0dbb9665
2. Rebuild solution from within Visual Studio

# Expected behavior

The build should succeed.

# Actual behavior

I get the following errors:
```
Error	LNK2001	unresolved external symbol "public: __cdecl Microsoft::Console::Render::GdiEngine::GdiEngine(void)" (??0GdiEngine@Render@Console@Microsoft@@QEAA@XZ)	UnitTests_TerminalCore	\terminal\src\cascadia\UnitTests_TerminalCore\ConInteractivityWin32Lib.lib(Window.obj)	1	
Error	LNK2001	unresolved external symbol "public: long __cdecl Microsoft::Console::Render::GdiEngine::SetHwnd(struct HWND__ * const)" (?SetHwnd@GdiEngine@Render@Console@Microsoft@@QEAAJQEAUHWND__@@@Z)	UnitTests_TerminalCore	\terminal\src\cascadia\UnitTests_TerminalCore\ConInteractivityWin32Lib.lib(Window.obj)	1	
Error	LNK1120	2 unresolved externals	UnitTests_TerminalCore	\terminal\bin\x64\Release\Terminal.Core.Unit.Tests.dll	1	
```

If I checkout one revision back (77dd51af39d4f083403bbbe34052f6bdcada9ec3), the build succeeds.

Is this just me, or is something busted?

**Comment by j4james** [comment]
Looking at the [results for the merge build](https://dev.azure.com/ms/Terminal/_build/results?buildId=58951&view=results), there are errors reported, but that just appears to be a timeout while running the unit tests, which doesn't necessarily indicate a problem. And the build in the PR (#4213) was definitely successful. Maybe it is just me.

**Comment by mkitzan** [comment]
My fork also fails to build with the same linker errors after the latest commit.

**Comment by zadjii-msft** [comment]
You might be able to work around this by building GdiRenderer manually. I think I missed that in the dependencies for that project, but didn't catch it since GdiRenderer.lib was already built on my machine.

I can take more of a look probably Wednesday at the earliest

**Comment by j4james** [comment]
> You might be able to work around this by building GdiRenderer manually.

That didn't seem to help, but what did work for me was adding _RendererGdi_ as a reference in the _UnitTests_TerminalCore_ project. I don't know if that's the right solution, but it does at least build.

For now, though, I'm just branching off the previous commit, so it's not a major problem.
